// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Model struct {
	Str                           types.String `tfsdk:"str"`
	CreateCompletionRequestModel2 types.String `tfsdk:"create_completion_request_model_2"`
}
